{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  hosts:
    {{- range .Values.istio.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  gateways:
    {{- range .Values.istio.virtualService.gateways }}
    - {{ . }}
    {{- end }}
  http:
    {{- range .Values.istio.virtualService.http }}
    - match:
        {{- range .match }}
        - uri:
            {{- if .uri.prefix }}
            prefix: {{ .uri.prefix }}
            {{- end }}
            {{- if .uri.exact }}
            exact: {{ .uri.exact }}
            {{- end }}
        {{- end }}
      route:
        {{- range .route }}
        - destination:
            host: {{ include "app.fullname" $ }}
            port:
              number: {{ $.Values.service.port }}
            {{- if .weight }}
          weight: {{ .weight }}
          {{- end }}
        {{- end }}
      {{- if .timeout }}
      timeout: {{ .timeout }}
      {{- end }}
      {{- if .retries }}
      retries:
        {{- toYaml .retries | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}