# Development Environment Helm Values
replicaCount: 1

image:
  repository: gcr.io/crucial-study-475405-e4/app
  tag: "dev-latest"

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "app-dev@crucial-study-475405-e4.iam.gserviceaccount.com"

env:
  - name: ENVIRONMENT
    value: "dev"
  - name: LOG_LEVEL
    value: "debug"

database:
  external:
    enabled: true
    secretName: "app-dev-db-credentials"

secretManager:
  enabled: true
  secretName: "app-dev-db-credentials"
  projectId: "crucial-study-475405-e4"

ingress:
  enabled: true
  hosts:
    - host: app-dev.example.com
      paths:
        - path: /
          pathType: Prefix

istio:
  enabled: true
  virtualService:
    enabled: true
    hosts:
      - app-dev.example.com
    gateways:
      - app-dev-gateway

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

monitoring:
  enabled: true