# Development Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-dev-tls-secret
  namespace: dev
spec:
  secretName: app-dev-tls-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - app-dev.inc.com